### ISSUE TITLE
rdf/ttl export causes out of memory due to growing aggregate datasets

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#232]
temporarily halting the production of ttl archives.

```
2016-05-19 06:20:41,297 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247450] of [248050] studies...
2016-05-19 06:20:41,363 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247500] of [248050] studies...
2016-05-19 06:20:41,425 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247550] of [248050] studies...
2016-05-19 06:20:41,453 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247600] of [248050] studies...
2016-05-19 06:20:41,512 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247650] of [248050] studies...
2016-05-19 06:20:41,567 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247700] of [248050] studies...
2016-05-19 06:20:41,601 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247750] of [248050] studies...
2016-05-19 06:20:46,172 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247800] of [248050] studies...
2016-05-19 06:20:46,210 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247850] of [248050] studies...
2016-05-19 06:20:46,317 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247900] of [248050] studies...
2016-05-19 06:20:46,342 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [247950] of [248050] studies...
2016-05-19 06:20:46,376 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [248000] of [248050] studies...
2016-05-19 06:20:46,430 [main] INFO  org.eol.globi.export.GraphExporterImpl - added triples for [248050] of [248050] studies...
2016-05-19 06:20:46,430 [main] INFO  org.eol.globi.export.GraphExporterImpl - adding triples for [248050] of [248050] studies.
2016-05-19 06:20:47,295 [main] INFO  org.eol.globi.export.GraphExporterImpl - writing turtle archive...
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:111)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:194)
	at org.apache.jena.atlas.io.IndentedWriter.write$(IndentedWriter.java:165)
	at org.apache.jena.atlas.io.IndentedWriter.printOneChar(IndentedWriter.java:160)
	at org.apache.jena.atlas.io.IndentedWriter.print(IndentedWriter.java:100)
	at org.apache.jena.riot.out.NodeFormatterTTL.formatURI(NodeFormatterTTL.java:69)
	at org.apache.jena.riot.out.NodeFormatterBase.formatURI(NodeFormatterBase.java:49)
	at org.apache.jena.riot.out.NodeFormatterBase.format(NodeFormatterBase.java:37)
	at org.apache.jena.riot.writer.WriterStreamRDFBase.outputNode(WriterStreamRDFBase.java:149)
	at org.apache.jena.riot.writer.WriterStreamRDFBlocks.writePredicateObjectList(WriterStreamRDFBlocks.java:161)
	at org.apache.jena.riot.writer.WriterStreamRDFBlocks.printBatch(WriterStreamRDFBlocks.java:140)
	at org.apache.jena.riot.writer.WriterStreamRDFBlocks.printBatchTriples(WriterStreamRDFBlocks.java:125)
	at org.apache.jena.riot.writer.WriterStreamRDFBatched.finishBatchTriple(WriterStreamRDFBatched.java:125)
	at org.apache.jena.riot.writer.WriterStreamRDFBatched.print(WriterStreamRDFBatched.java:103)
	at org.apache.jena.riot.writer.WriterStreamRDFBase.triple(WriterStreamRDFBase.java:111)
	at org.apache.jena.riot.system.StreamRDFLib.triplesToStream(StreamRDFLib.java:82)
	at org.apache.jena.riot.writer.WriterStream.write(WriterStream.java:72)
	at org.apache.jena.riot.writer.TurtleWriterBlocks.output(TurtleWriterBlocks.java:36)
	at org.apache.jena.riot.writer.TurtleWriterBase.output$(TurtleWriterBase.java:55)
	at org.apache.jena.riot.writer.TurtleWriterBase.write(TurtleWriterBase.java:43)
	at org.apache.jena.riot.RDFDataMgr.write$(RDFDataMgr.java:1268)
	at org.apache.jena.riot.RDFDataMgr.write(RDFDataMgr.java:1074)
	at org.eol.globi.export.LittleTurtleExporter.exportDataOntology(LittleTurtleExporter.java:196)
	at org.eol.globi.export.GraphExporterImpl.exportDataOntology(GraphExporterImpl.java:156)
	at org.eol.globi.export.GraphExporterImpl.export(GraphExporterImpl.java:58)
	at org.eol.globi.tool.Normalizer.exportData(Normalizer.java:211)
	at org.eol.globi.tool.Normalizer.exportData(Normalizer.java:103)
	at org.eol.globi.tool.Normalizer.run(Normalizer.java:93)
	at org.eol.globi.tool.Normalizer.main(Normalizer.java:61)
neo4j stopping...
neo4j stopped.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8:53:15.070s
[INFO] Finished at: Thu May 19 06:58:17 CEST 2016
[INFO] Final Memory: 13M/481M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "generate-datasets" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default) on project eol-globi-datasets: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] Scanning for projects...
Downloading: https://oss.sonatype.org/content/repositories/snapshots/joda-time/joda-time/maven-metadata.xml

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building EOL's Global Biotic Interaction Datasets 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ eol-globi-datasets ---
[INFO] Deleting /home/jhpoelen/eol-globi-data/eol-globi-datasets/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.178s
[INFO] Finished at: Thu May 19 06:58:20 CEST 2016
[INFO] Final Memory: 14M/481M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "generate-datasets" could not be activated because it does not exist.
Releasing lock [/home/jhpoelen/indexing.lock]
```

**Comment by jhpoelen** [comment]
@cmungall I'd like to suggest to switch to generating stream of n-quads to avoid having to build up a giant triple store, only to export the triples soon after. Converting existing functionality would look like. Please note that taxonIds are a bit hacked and are for instruction purposes only. Ideally, we'd replace the blank nodes with absolute and resolvable IRIs pointing to the originating dataset. 

```
_:BX2D1b067814X3A1566b615932X3AX2D7ff4 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ff5 .
_:BX2D1b067814X3A1566b615932X3AX2D7ff4 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ff6 .
_:BX2D1b067814X3A1566b615932X3AX2D7ff4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7fee <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fef .
_:BX2D1b067814X3A1566b615932X3AX2D7fee <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ff0 .
_:BX2D1b067814X3A1566b615932X3AX2D7fee <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe4 <http://purl.obolibrary.org/obo/RO_0002471> _:BX2D1b067814X3A1566b615932X3AX2D7fe3 .
_:BX2D1b067814X3A1566b615932X3AX2D7fe4 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Pygospio elegans> .
_:BX2D1b067814X3A1566b615932X3AX2D7ffd <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ffe .
_:BX2D1b067814X3A1566b615932X3AX2D7ffd <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fff .
_:BX2D1b067814X3A1566b615932X3AX2D7ffd <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff3 <http://purl.obolibrary.org/obo/RO_0002470> _:BX2D1b067814X3A1566b615932X3AX2D7ff2 .
_:BX2D1b067814X3A1566b615932X3AX2D7ff3 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/invertebrates> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff3 <http://purl.obolibrary.org/obo/BFO_0000066> <http://purl.obolibrary.org/obo/ENVO_00000233> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff9 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff9 <http://purl.obolibrary.org/obo/RO_0002470> _:BX2D1b067814X3A1566b615932X3AX2D7ff8 .
_:BX2D1b067814X3A1566b615932X3AX2D7ff9 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Syngnathus scovelli> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff9 <http://purl.obolibrary.org/obo/BFO_0000066> <http://purl.obolibrary.org/obo/ENVO_01000020> .
_:BX2D1b067814X3A1566b615932X3AX2D7fed <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fed <http://purl.obolibrary.org/obo/RO_0002470> _:BX2D1b067814X3A1566b615932X3AX2D7fec .
_:BX2D1b067814X3A1566b615932X3AX2D7fed <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Pycnocentrodes> .
_:BX2D1b067814X3A1566b615932X3AX2D7fed <http://purl.obolibrary.org/obo/BFO_0000066> <http://purl.obolibrary.org/obo/ENVO_00000022> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe3 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Platichthys flesus> .
_:BX2D1b067814X3A1566b615932X3AX2D7ffc <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ffc <http://purl.obolibrary.org/obo/RO_0002471> _:BX2D1b067814X3A1566b615932X3AX2D7ffb .
_:BX2D1b067814X3A1566b615932X3AX2D7ffc <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Engraulidae> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe9 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe9 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Pycnocentrodes> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff2 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/detritivorous invertebrates> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff8 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/algae> .
_:BX2D1b067814X3A1566b615932X3AX2D7fec <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fec <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Navicula rhynchocephala> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe2 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fe3 .
_:BX2D1b067814X3A1566b615932X3AX2D7fe2 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fe4 .
_:BX2D1b067814X3A1566b615932X3AX2D7fe2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7ffb <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ffb <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Cephalopoda> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe8 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fe9 .
_:BX2D1b067814X3A1566b615932X3AX2D7fe8 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fea .
_:BX2D1b067814X3A1566b615932X3AX2D7fe8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff1 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ff2 .
_:BX2D1b067814X3A1566b615932X3AX2D7ff1 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ff3 .
_:BX2D1b067814X3A1566b615932X3AX2D7ff1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff7 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ff8 .
_:BX2D1b067814X3A1566b615932X3AX2D7ff7 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ff9 .
_:BX2D1b067814X3A1566b615932X3AX2D7ff7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7feb <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fec .
_:BX2D1b067814X3A1566b615932X3AX2D7feb <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fed .
_:BX2D1b067814X3A1566b615932X3AX2D7feb <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7ffa <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ffb .
_:BX2D1b067814X3A1566b615932X3AX2D7ffa <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7ffc .
_:BX2D1b067814X3A1566b615932X3AX2D7ffa <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe7 <http://purl.obolibrary.org/obo/RO_0002470> _:BX2D1b067814X3A1566b615932X3AX2D7fe6 .
_:BX2D1b067814X3A1566b615932X3AX2D7fe7 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Platichthys flesus> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe7 <http://purl.obolibrary.org/obo/BFO_0000066> <http://purl.obolibrary.org/obo/ENVO_01000020> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff0 <http://purl.obolibrary.org/obo/RO_0002471> _:BX2D1b067814X3A1566b615932X3AX2D7fef .
_:BX2D1b067814X3A1566b615932X3AX2D7ff0 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/detritivorous invertebrates> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff6 <http://purl.obolibrary.org/obo/RO_0002471> _:BX2D1b067814X3A1566b615932X3AX2D7ff5 .
_:BX2D1b067814X3A1566b615932X3AX2D7ff6 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/algae> .
_:BX2D1b067814X3A1566b615932X3AX2D7fea <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fea <http://purl.obolibrary.org/obo/RO_0002471> _:BX2D1b067814X3A1566b615932X3AX2D7fe9 .
_:BX2D1b067814X3A1566b615932X3AX2D7fea <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Navicula rhynchocephala> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe6 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Pygospio elegans> .
_:BX2D1b067814X3A1566b615932X3AX2D7fff <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fff <http://purl.obolibrary.org/obo/RO_0002470> _:BX2D1b067814X3A1566b615932X3AX2D7ffe .
_:BX2D1b067814X3A1566b615932X3AX2D7fff <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Cephalopoda> .
_:BX2D1b067814X3A1566b615932X3AX2D7fff <http://purl.obolibrary.org/obo/BFO_0000066> <http://purl.obolibrary.org/obo/ENVO_00000447> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ff5 <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Syngnathus scovelli> .
_:BX2D1b067814X3A1566b615932X3AX2D7fef <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7fef <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/invertebrates> .
_:BX2D1b067814X3A1566b615932X3AX2D7fe5 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fe6 .
_:BX2D1b067814X3A1566b615932X3AX2D7fe5 <http://purl.obolibrary.org/obo/RO_0000057> _:BX2D1b067814X3A1566b615932X3AX2D7fe7 .
_:BX2D1b067814X3A1566b615932X3AX2D7fe5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/GO_0044419> .
_:BX2D1b067814X3A1566b615932X3AX2D7ffe <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0010004> .
_:BX2D1b067814X3A1566b615932X3AX2D7ffe <http://purl.obolibrary.org/obo/RO_0002350> <http://eol.org/pages/Engraulidae> .
```

**Comment by jhpoelen** [comment]
nquad data export has been implemented. Waiting for first version of .nq artifact to be produced.

**Comment by jhpoelen** [comment]
nq archives are now being produced . . . and available through http://lod.globalbioticinteractions.org . Note that we are only scratching the surface on the exposing GloBI data: many of the valuable data elements are not yet (fully) exposed. Given the simplicity of the nq export, adding more relations should be relatively straight forward once the appropriate terms and ontologies are selected.
