### ISSUE TITLE
name resolution with iNaturalist fails due to iNaturalist api time-outs

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#333]
It appears that requests to resolve inat taxa are timing out during a taxon match process. This causing the names coming from iNaturalist to be unresolved, resulting in low match percentages in status page (see attached image). 
![screenshot from 2018-01-19 08-10-44](https://user-images.githubusercontent.com/1084872/35159860-70e14866-fcf0-11e7-9a11-489ea182d17e.png)

Some representative error messages -
```
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to api.inaturalist.org:80 [api.inaturalist.org/51.143.
21.6] failed: Connection timed out (Connection timed out)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:
318)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:82)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136)
        at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:119)
        ... 17 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
        ... 30 more
TaxonEnricherImpl:72 - skipping taxon match against [class org.eol.globi.taxon.INaturalistTaxonServic
e], error count [11] too high.

**Comment by jhpoelen** [comment]
Turned out there were several issues - first, Inaturalist api seems to have imposed more strict api limits, preventing GloBI from checking taxa 1k's of taxa without waiting too much. Second, GloBI index builder didn't previously use the cached inaturalist taxonomies.

For now, GloBI index builder *is* using the cached inaturalist taxa, which removes the need to re-resolve 1000s of iNaturalist taxa every couple of days. By using the cached taxa, any changes in the taxonomy itself (name changes, taxon merges) will not be updated until the taxa are re-resolved from scratch. 

Will close issue after confirming that a newer GloBI index has incorporated the cached taxa as expected.

**Comment by jhpoelen** [comment]
Note that the recent failure of https://travis-ci.org/ropensci/rglobi is a direct result of this issue - most human food related interactions come from iNaturalist.

**Comment by jhpoelen** [comment]
iNaturalist taxon api timeouts resolved by using cached version of iNaturalist taxa. After the changes propagated over the weekend, the taxon match rate is up from 15% to 97% (see attached screenshot) and rglobi's test cases are passing. 

![screenshot from 2018-01-22 11-20-04](https://user-images.githubusercontent.com/1084872/35239885-931b203c-ff66-11e7-8e92-5164c8754861.png)
